#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=ExampleJob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module load 2025
module load Python/3.13.1-GCCcore-14.2.0
module load CUDA/12.8.0

# Your job starts in the directory where you call sbatch
cd $HOME/Assignment\ 2
# Activate your environment
source /projects/prjs1945/venv/bin/activate
# Run your code
srun python -u main_CNN.py